version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser", "es2022", "node"]
  style_guide = "airbnb"
  skip_doc_coverage = ["node_modules", "dist", "build"]
  dialect = "typescript"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[exclude_patterns]]
name = "node_modules"

[[exclude_patterns]]
name = "dist"

[[exclude_patterns]]
name = "build"

[[exclude_patterns]]
name = "*.min.js"

[[transformers]]
name = "prettier"
enabled = true
