/**
 * codeTemplates.ts - Code generation templates for Module Builder
 *
 * Phase 3.1 of Module Builder
 *
 * Purpose:
 * Transforms JSON module definitions into production-ready TypeScript/React code
 * that follows all existing platform patterns and standards.
 *
 * Template Requirements:
 * - TypeScript interfaces for all props
 * - Accessibility compliance (WCAG 2.1 AA)
 * - Dev Mode integration
 * - Progress Persistence integration
 * - AI Validation integration (for reflection activities)
 * - Self-contained module pattern
 * - Certificate generation
 *
 * Template Variables (use double curly braces):
 * - {{MODULE_NAME}} - PascalCase module name
 * - {{MODULE_ID}} - kebab-case module ID
 * - {{MODULE_TITLE}} - Display title
 * - {{MODULE_DESCRIPTION}} - Description
 * - {{ESTIMATED_TIME}} - e.g., "20 min"
 * - {{USER_NAME}} - userName prop (passed from parent)
 * - {{ACTIVITIES}} - JSON array of activity configs
 * - {{VIDEO_URL}} - Video URL for video activities
 * - {{VIDEO_SEGMENTS}} - JSON array of video segments
 *
 * Usage:
 * ```typescript
 * const moduleCode = generateModuleCode(moduleDefinition);
 * const activityCode = generateActivityCode(activityDefinition);
 * ```
 */

/**
 * Module container template - main wrapper component
 */
export const MODULE_CONTAINER_TEMPLATE = `import React, { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useActivityRegistry } from '@/context/ActivityRegistryContext';
import { saveProgress, loadProgress, clearProgress, getProgressSummary } from '@/lib/progressPersistence';
import ResumeProgressDialog from '@/components/shared/ResumeProgressDialog';
import CertificateActivity from '@/components/shared/CertificateActivity';

/**
 * {{MODULE_NAME}} - {{MODULE_DESCRIPTION}}
 *
 * **Generated by Module Builder** - {{GENERATED_DATE}}
 *
 * Estimated Time: {{ESTIMATED_TIME}}
 * Target Audience: {{TARGET_AUDIENCE}}
 *
 * Features:
 * - Self-contained module with {{ACTIVITY_COUNT}} activities
 * - Progress persistence (resume on refresh)
 * - Developer Mode integration (Ctrl+Alt+D navigation)
 * - Certificate generation on completion
 * - Accessibility compliant (WCAG 2.1 AA)
 *
 * Module Structure:
 {{ACTIVITY_LIST}}
 */

interface {{MODULE_NAME}}Props {
  userName: string;
  onClose?: () => void;
}

const MODULE_ID = '{{MODULE_ID}}';
const MODULE_VERSION = '1.0.0';

export default function {{MODULE_NAME}}({ userName, onClose }: {{MODULE_NAME}}Props) {
  const [currentActivity, setCurrentActivity] = useState(0);
  const [activities, setActivities] = useState<{ id: string; title: string; completed: boolean }[]>([
    {{ACTIVITY_DEFINITIONS}}
  ]);

  const [savedProgress, setSavedProgress] = useState<any>(null);
  const [showResumeDialog, setShowResumeDialog] = useState(false);

  const { registerActivity, clearRegistry } = useActivityRegistry();

  // Load progress on mount
  useEffect(() => {
    const progress = loadProgress(MODULE_ID, activities);
    if (progress) {
      setSavedProgress(getProgressSummary(MODULE_ID));
      setShowResumeDialog(true);
    }
  }, []);

  // Register activities with Dev Mode (ONCE on mount)
  useEffect(() => {
    clearRegistry();
    activities.forEach((activity, index) => {
      registerActivity({
        id: activity.id,
        title: activity.title,
        type: 'activity', // Generic type
        moduleId: MODULE_ID,
        index,
      });
    });
  }, []); // Empty deps - only register once

  // Listen for Dev Mode navigation
  useEffect(() => {
    const handleGoToActivity = (event: CustomEvent) => {
      setCurrentActivity(event.detail);
    };
    window.addEventListener('goToActivity', handleGoToActivity as EventListener);
    return () => window.removeEventListener('goToActivity', handleGoToActivity as EventListener);
  }, []);

  // Auto-save progress
  useEffect(() => {
    if (!showResumeDialog && currentActivity > 0) {
      saveProgress(MODULE_ID, currentActivity, activities, MODULE_VERSION);
    }
  }, [currentActivity, activities, showResumeDialog]);

  const handleResumeProgress = () => {
    const progress = loadProgress(MODULE_ID, activities);
    if (progress) {
      setCurrentActivity(progress.currentActivity);
      setActivities(progress.activities);
    }
    setShowResumeDialog(false);
  };

  const handleStartFresh = () => {
    clearProgress(MODULE_ID);
    setShowResumeDialog(false);
  };

  const handleActivityComplete = () => {
    const updated = [...activities];
    updated[currentActivity].completed = true;
    setActivities(updated);

    if (currentActivity < activities.length - 1) {
      setCurrentActivity(currentActivity + 1);
    } else {
      // All activities complete, move to certificate
      setCurrentActivity(activities.length);
    }
  };

  const handleCertificateDownload = () => {
    clearProgress(MODULE_ID);
  };

  return (
    <>
      {showResumeDialog && savedProgress && (
        <ResumeProgressDialog
          savedProgress={savedProgress}
          onResume={handleResumeProgress}
          onStartFresh={handleStartFresh}
        />
      )}

      <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-100">
        {/* Header */}
        <header className="bg-white shadow-sm border-b border-gray-200">
          <div className="container mx-auto px-4 py-4 flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{{MODULE_TITLE}}</h1>
              <p className="text-sm text-gray-600">{{MODULE_DESCRIPTION}}</p>
            </div>
            {onClose && (
              <button
                onClick={onClose}
                className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
                aria-label="Close module"
              >
                <X className="w-5 h-5" />
              </button>
            )}
          </div>
        </header>

        {/* Main Content */}
        <main className="container mx-auto px-4 py-8">
          {{ACTIVITY_RENDERING}}

          {/* Certificate */}
          {currentActivity === activities.length && (
            <CertificateActivity
              userName={userName}
              moduleName="{{MODULE_TITLE}}"
              completionDate={new Date().toLocaleDateString()}
              onDownload={handleCertificateDownload}
            />
          )}
        </main>
      </div>
    </>
  );
}
`;

/**
 * Video activity template (PremiumVideoPlayer pattern)
 */
export const VIDEO_ACTIVITY_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-4xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-6">
      <h2 className="text-xl font-bold text-gray-900 mb-4">{{ACTIVITY_TITLE}}</h2>

      <PremiumVideoPlayer
        videoUrl="{{VIDEO_URL}}"
        videoId="{{VIDEO_ID}}"
        segments={[
          {{VIDEO_SEGMENTS}}
        ]}
        onAllSegmentsComplete={handleActivityComplete}
      />
    </div>
  </div>
)}`;

/**
 * Quiz activity template (multiple choice)
 */
export const QUIZ_ACTIVITY_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-3xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">{{ACTIVITY_TITLE}}</h2>

      {!quizComplete ? (
        <div>
          <p className="text-lg font-semibold text-gray-800 mb-4">
            Question {currentQuestion + 1} of {quizQuestions.length}
          </p>
          <p className="text-gray-900 mb-6">
            {quizQuestions[currentQuestion].question}
          </p>

          <div className="space-y-3 mb-6">
            {quizQuestions[currentQuestion].options.map((option, idx) => (
              <button
                key={idx}
                onClick={() => handleQuizAnswer(idx)}
                disabled={selectedAnswer !== null}
                className={\`w-full p-4 text-left rounded-lg border-2 transition-colors \${
                  selectedAnswer === idx
                    ? idx === quizQuestions[currentQuestion].correctAnswer
                      ? 'border-green-500 bg-green-50 text-green-900'
                      : 'border-red-500 bg-red-50 text-red-900'
                    : selectedAnswer !== null && idx === quizQuestions[currentQuestion].correctAnswer
                    ? 'border-green-500 bg-green-50 text-green-900'
                    : 'border-gray-300 bg-white hover:border-purple-300 hover:bg-purple-50'
                }\`}
              >
                <div className="flex items-start gap-3">
                  <span className="font-bold">{String.fromCharCode(65 + idx)}.</span>
                  <span>{option}</span>
                </div>
              </button>
            ))}
          </div>

          {selectedAnswer !== null && (
            <div className={\`p-4 rounded-lg \${
              selectedAnswer === quizQuestions[currentQuestion].correctAnswer
                ? 'bg-green-50 border border-green-200'
                : 'bg-red-50 border border-red-200'
            }\`}>
              <p className="text-sm font-semibold mb-2">
                {selectedAnswer === quizQuestions[currentQuestion].correctAnswer
                  ? '✅ Correct!'
                  : '❌ Incorrect'}
              </p>
              <p className="text-sm">
                {quizQuestions[currentQuestion].explanation}
              </p>
            </div>
          )}

          {selectedAnswer !== null && (
            <Button
              onClick={handleNextQuestion}
              className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
            >
              {currentQuestion < quizQuestions.length - 1 ? 'Next Question' : 'Complete Quiz'}
            </Button>
          )}
        </div>
      ) : (
        <div className="text-center">
          <p className="text-2xl font-bold text-green-600 mb-4">Quiz Complete!</p>
          <p className="text-gray-700 mb-6">
            You got {quizScore} out of {quizQuestions.length} correct.
          </p>
          <Button
            onClick={handleActivityComplete}
            className="bg-purple-600 hover:bg-purple-700 text-white"
          >
            Continue to Next Activity
          </Button>
        </div>
      )}
    </div>
  </div>
)}`;

/**
 * Reflection activity template (with AI validation)
 */
export const REFLECTION_ACTIVITY_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-3xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">{{ACTIVITY_TITLE}}</h2>

      <div className="mb-6 p-4 bg-purple-50 border border-purple-200 rounded-lg">
        <p className="text-gray-900">{{REFLECTION_PROMPT}}</p>
      </div>

      {{GUIDING_QUESTIONS}}

      <textarea
        value={reflectionResponse}
        onChange={(e) => setReflectionResponse(e.target.value)}
        placeholder="Type your reflection here... (minimum {{MIN_RESPONSE_LENGTH}} words)"
        className="w-full p-4 border border-gray-300 rounded-lg text-gray-900 focus:ring-2 focus:ring-purple-500 focus:border-transparent"
        rows={8}
        disabled={showFeedback && !needsRetry}
      />

      <p className="text-sm text-gray-600 mt-2">
        {reflectionResponse.split(/\\s+/).filter(w => w.length > 0).length} / {{MIN_RESPONSE_LENGTH}} words
      </p>

      {showFeedback && (
        <div className={\`mt-6 p-4 rounded-lg border-2 \${
          needsRetry ? 'bg-yellow-50 border-yellow-300' : 'bg-green-50 border-green-300'
        }\`}>
          <p className="text-sm font-semibold mb-2">
            {needsRetry ? '⚠️ Feedback:' : '✅ Great reflection!'}
          </p>
          <p className="text-sm">{feedback}</p>
        </div>
      )}

      {showEscapeHatch && needsRetry && (
        <div className="mt-6 p-4 bg-orange-50 border-2 border-orange-300 rounded-lg">
          <p className="text-sm font-semibold text-orange-900 mb-3">
            ⚠️ You've attempted this reflection {attemptCount} times. Choose one:
          </p>
          <div className="flex gap-3">
            <Button
              onClick={handleTryAgain}
              variant="outline"
              className="flex-1 border-orange-300 text-orange-700 hover:bg-orange-100"
            >
              Try One More Time
            </Button>
            <Button
              onClick={handleContinueAnyway}
              className="flex-1 bg-orange-600 hover:bg-orange-700 text-white"
            >
              Continue Anyway
            </Button>
          </div>
          <p className="text-xs text-orange-600 mt-2">
            Note: Bypassing will be flagged for instructor review.
          </p>
        </div>
      )}

      {!showFeedback && (
        <Button
          onClick={handleSubmitReflection}
          disabled={isGeneratingFeedback}
          className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
        >
          {isGeneratingFeedback ? 'Analyzing...' : 'Submit Reflection'}
        </Button>
      )}

      {showFeedback && !needsRetry && (
        <Button
          onClick={handleActivityComplete}
          className="mt-6 bg-green-600 hover:bg-green-700 text-white"
        >
          Continue to Next Activity
        </Button>
      )}

      {showFeedback && needsRetry && !showEscapeHatch && (
        <Button
          onClick={handleTryAgain}
          variant="outline"
          className="mt-6 border-yellow-600 text-yellow-700 hover:bg-yellow-50"
        >
          Try Again
        </Button>
      )}
    </div>
  </div>
)}`;

/**
 * Interactive activity template (placeholder for custom interactives)
 */
export const INTERACTIVE_ACTIVITY_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-5xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">{{ACTIVITY_TITLE}}</h2>

      <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 text-center">
        <p className="text-gray-700 mb-4">
          {{ACTIVITY_DESCRIPTION}}
        </p>
        <p className="text-sm text-gray-600">
          ⚠️ Custom interactive component requires manual implementation.
        </p>
      </div>

      <Button
        onClick={handleActivityComplete}
        className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
      >
        Continue to Next Activity
      </Button>
    </div>
  </div>
)}`;

/**
 * Scenario activity template (ethical dilemma)
 */
export const SCENARIO_ACTIVITY_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-4xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">{{ACTIVITY_TITLE}}</h2>

      {/* Context */}
      <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <p className="text-sm font-semibold text-blue-900 mb-2">📖 Scenario Context:</p>
        <p className="text-gray-800 whitespace-pre-wrap">{{SCENARIO_CONTEXT}}</p>
      </div>

      {/* The Dilemma */}
      <div className="mb-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
        <p className="text-sm font-semibold text-yellow-900 mb-2">⚠️ The Ethical Dilemma:</p>
        <p className="text-gray-900 font-medium">{{SCENARIO_DILEMMA}}</p>
      </div>

      {/* Stakeholders */}
      <div className="mb-6">
        <p className="text-sm font-semibold text-gray-700 mb-2">👥 Stakeholders:</p>
        <div className="flex flex-wrap gap-2">
          {{STAKEHOLDER_CHIPS}}
        </div>
      </div>

      {/* Guiding Questions */}
      <div className="mb-6">
        <p className="text-sm font-semibold text-gray-700 mb-3">❓ Consider these questions:</p>
        <ul className="space-y-2">
          {{GUIDING_QUESTIONS_LIST}}
        </ul>
      </div>

      {/* Student Response */}
      <textarea
        value={scenarioResponse}
        onChange={(e) => setScenarioResponse(e.target.value)}
        placeholder="Analyze the ethical dilemma and explain your reasoning..."
        className="w-full p-4 border border-gray-300 rounded-lg text-gray-900"
        rows={8}
      />

      <Button
        onClick={handleScenarioSubmit}
        disabled={scenarioResponse.trim().length < 100}
        className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
      >
        Submit Analysis
      </Button>
    </div>
  </div>
)}`;

/**
 * Exit ticket activity template
 */
export const EXIT_TICKET_TEMPLATE = `{currentActivity === {{ACTIVITY_INDEX}} && (
  <div className="max-w-3xl mx-auto">
    <div className="bg-white rounded-xl shadow-lg p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Exit Ticket</h2>

      <p className="text-gray-700 mb-6">
        Choose one reflection prompt to complete before finishing this module:
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        {{EXIT_TICKET_OPTIONS}}
      </div>

      {selectedPrompt && (
        <div className="mt-6">
          <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg mb-4">
            <p className="text-gray-900">{selectedPrompt.prompt}</p>
          </div>

          <textarea
            value={exitTicketResponse}
            onChange={(e) => setExitTicketResponse(e.target.value)}
            placeholder="Type your reflection here..."
            className="w-full p-4 border border-gray-300 rounded-lg text-gray-900"
            rows={6}
          />

          <Button
            onClick={handleExitTicketSubmit}
            disabled={exitTicketResponse.trim().length < 100}
            className="mt-4 bg-purple-600 hover:bg-purple-700 text-white"
          >
            Submit Exit Ticket
          </Button>
        </div>
      )}
    </div>
  </div>
)}`;

/**
 * Generate complete module code from definition
 */
export function generateModuleCode(moduleDefinition: any): string {
  // TODO: Implementation in Phase 3.2
  return MODULE_CONTAINER_TEMPLATE;
}

/**
 * Generate activity-specific code
 */
export function generateActivityCode(activityDefinition: any): string {
  // TODO: Implementation in Phase 3.2
  return '';
}

/**
 * Helper: Generate TypeScript imports
 */
export function generateImports(activityTypes: string[]): string {
  const imports = new Set<string>([
    "import React, { useState, useEffect } from 'react';",
    "import { X } from 'lucide-react';",
    "import { Button } from '@/components/ui/button';",
    "import { useActivityRegistry } from '@/context/ActivityRegistryContext';",
    "import { saveProgress, loadProgress, clearProgress, getProgressSummary } from '@/lib/progressPersistence';",
    "import ResumeProgressDialog from '@/components/shared/ResumeProgressDialog';",
    "import CertificateActivity from '@/components/shared/CertificateActivity';",
  ]);

  if (activityTypes.includes('video')) {
    imports.add("import PremiumVideoPlayer from '@/components/shared/PremiumVideoPlayer';");
  }

  if (activityTypes.includes('reflection')) {
    imports.add("import { generateEducationFeedback, isNonsensical } from '@/utils/aiEducationFeedback';");
  }

  return Array.from(imports).join('\n');
}

/**
 * Helper: Generate TypeScript interface
 */
export function generateInterface(moduleName: string): string {
  return `interface ${moduleName}Props {
  userName: string;
  onClose?: () => void;
}`;
}
