/**
 * codeGenerator.ts - TypeScript/React code generator for Module Builder
 *
 * Phase 3.2 of Module Builder
 *
 * Purpose:
 * Transforms JSON module definitions into production-ready TypeScript/React code.
 * Uses templates from codeTemplates.ts and performs string substitution.
 *
 * Features:
 * - Complete module file generation (1000+ lines of TypeScript)
 * - Activity-specific code generation
 * - Proper formatting (Prettier-compatible)
 * - Type safety validation
 * - Follows all platform patterns (Dev Mode, Progress Persistence, AI Validation)
 *
 * Usage:
 * ```typescript
 * const code = generateCompleteModule(moduleDefinition);
 * downloadCode(code, `${moduleDefinition.id}.tsx`);
 * ```
 */

import {
  MODULE_CONTAINER_TEMPLATE,
  VIDEO_ACTIVITY_TEMPLATE,
  QUIZ_ACTIVITY_TEMPLATE,
  REFLECTION_ACTIVITY_TEMPLATE,
  INTERACTIVE_ACTIVITY_TEMPLATE,
  SCENARIO_ACTIVITY_TEMPLATE,
  EXIT_TICKET_TEMPLATE,
  generateImports,
  generateInterface,
} from './codeTemplates';

/**
 * Module definition structure (from ModuleAssembly)
 */
export interface ModuleDefinition {
  id: string;
  title: string;
  description: string;
  targetAudience: string;
  estimatedTime: string;
  activities: ActivityConfig[];
  videos: any[];
  metadata: {
    author: string;
    version: string;
    createdAt: string;
    updatedAt: string;
  };
}

export interface ActivityConfig {
  id: string;
  type: string;
  name: string;
  position: number;
  props: Record<string, any>;
  notes?: string;
}

/**
 * Generate complete module TypeScript file
 */
export function generateCompleteModule(definition: ModuleDefinition): string {
  const moduleName = toPascalCase(definition.id);
  const activityTypes = definition.activities.map((a) => a.type);

  // 1. Generate imports
  const imports = generateImports(activityTypes);

  // 2. Generate module header comment
  const header = generateModuleHeader(definition);

  // 3. Generate interface
  const interfaceCode = generateInterface(moduleName);

  // 4. Generate activity definitions
  const activityDefinitions = generateActivityDefinitions(definition.activities);

  // 5. Generate state declarations
  const stateDeclarations = generateStateDeclarations(definition.activities);

  // 6. Generate activity data
  const activityData = generateActivityData(definition.activities);

  // 7. Generate activity handlers
  const activityHandlers = generateActivityHandlers(definition.activities);

  // 8. Generate activity rendering
  const activityRendering = generateActivityRendering(definition.activities);

  // 9. Assemble complete file
  let code = imports + '\n\n';
  code += header + '\n\n';
  code += interfaceCode + '\n\n';
  code += `const MODULE_ID = '${definition.id}';\n`;
  code += `const MODULE_VERSION = '${definition.metadata.version}';\n\n`;
  code += `export default function ${moduleName}({ userName, onClose }: ${moduleName}Props) {\n`;
  code += '  // State\n';
  code += '  const [currentActivity, setCurrentActivity] = useState(0);\n';
  code += stateDeclarations + '\n';
  code += '  const [activities, setActivities] = useState<{ id: string; title: string; completed: boolean }[]>([\n';
  code += activityDefinitions + '\n';
  code += '  ]);\n\n';
  code += '  const [savedProgress, setSavedProgress] = useState<any>(null);\n';
  code += '  const [showResumeDialog, setShowResumeDialog] = useState(false);\n\n';
  code += '  const { registerActivity, clearRegistry } = useActivityRegistry();\n\n';
  code += generateProgressPersistenceLogic();
  code += '\n\n';
  code += generateDevModeIntegration();
  code += '\n\n';
  code += activityData;
  code += '\n\n';
  code += activityHandlers;
  code += '\n\n';
  code += generateStandardHandlers();
  code += '\n\n';
  code += '  return (\n';
  code += '    <>\n';
  code += generateResumeDialog();
  code += '\n';
  code += `      <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-100">\n`;
  code += generateHeader(definition.title, definition.description);
  code += '\n';
  code += '        <main className="container mx-auto px-4 py-8">\n';
  code += activityRendering;
  code += '\n\n';
  code += generateCertificate(definition.title);
  code += '\n';
  code += '        </main>\n';
  code += '      </div>\n';
  code += '    </>\n';
  code += '  );\n';
  code += '}\n';

  return code;
}

/**
 * Convert kebab-case to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Generate module header comment
 */
function generateModuleHeader(definition: ModuleDefinition): string {
  const date = new Date().toLocaleDateString();
  return `/**
 * ${toPascalCase(definition.id)} - ${definition.description}
 *
 * **Generated by Module Builder** - ${date}
 *
 * Estimated Time: ${definition.estimatedTime}
 * Target Audience: ${definition.targetAudience}
 * Author: ${definition.metadata.author}
 *
 * Features:
 * - Self-contained module with ${definition.activities.length} activities
 * - Progress persistence (resume on refresh)
 * - Developer Mode integration (Ctrl+Alt+D navigation)
 * - Certificate generation on completion
 * - Accessibility compliant (WCAG 2.1 AA)
 *
 * Module Structure:
${definition.activities.map((a, i) => ` * ${i + 1}. ${a.name} (${a.type})`).join('\n')}
 * ${definition.activities.length + 1}. Certificate of Completion
 */`;
}

/**
 * Generate activity definitions for state initialization
 */
function generateActivityDefinitions(activities: ActivityConfig[]): string {
  return activities
    .map(
      (a) => `    { id: '${a.id}', title: '${a.name}', completed: false },`
    )
    .join('\n');
}

/**
 * Generate state declarations for each activity type
 */
function generateStateDeclarations(activities: ActivityConfig[]): string {
  const declarations: string[] = [];

  if (activities.some((a) => a.type === 'quiz')) {
    declarations.push(
      '  const [currentQuestion, setCurrentQuestion] = useState(0);',
      '  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);',
      '  const [quizScore, setQuizScore] = useState(0);',
      '  const [quizComplete, setQuizComplete] = useState(false);'
    );
  }

  if (activities.some((a) => a.type === 'reflection')) {
    declarations.push(
      '  const [reflectionResponse, setReflectionResponse] = useState(\'\');',
      '  const [feedback, setFeedback] = useState(\'\');',
      '  const [showFeedback, setShowFeedback] = useState(false);',
      '  const [needsRetry, setNeedsRetry] = useState(false);',
      '  const [isGeneratingFeedback, setIsGeneratingFeedback] = useState(false);',
      '  const [attemptCount, setAttemptCount] = useState(0);',
      '  const [showEscapeHatch, setShowEscapeHatch] = useState(false);',
      '  const MAX_ATTEMPTS = 2;'
    );
  }

  if (activities.some((a) => a.type === 'scenario')) {
    declarations.push(
      '  const [scenarioResponse, setScenarioResponse] = useState(\'\');'
    );
  }

  if (activities.some((a) => a.type === 'exit-ticket')) {
    declarations.push(
      '  const [selectedPrompt, setSelectedPrompt] = useState<any>(null);',
      '  const [exitTicketResponse, setExitTicketResponse] = useState(\'\');'
    );
  }

  return declarations.join('\n');
}

/**
 * Generate activity data (quiz questions, reflection prompts, etc.)
 */
function generateActivityData(activities: ActivityConfig[]): string {
  let code = '';

  activities.forEach((activity, index) => {
    if (activity.type === 'quiz' && activity.props.questions) {
      code += `  // Quiz questions for Activity ${index + 1}\n`;
      code += `  const quizQuestions = ${JSON.stringify(activity.props.questions, null, 2)};\n\n`;
    }

    if (activity.type === 'exit-ticket' && activity.props.prompts) {
      code += `  // Exit ticket prompts for Activity ${index + 1}\n`;
      code += `  const exitTicketPrompts = ${JSON.stringify(activity.props.prompts, null, 2)};\n\n`;
    }
  });

  return code;
}

/**
 * Generate activity handlers
 */
function generateActivityHandlers(activities: ActivityConfig[]): string {
  let code = '';

  if (activities.some((a) => a.type === 'quiz')) {
    code += `  const handleQuizAnswer = (answerIndex: number) => {
    setSelectedAnswer(answerIndex);
    if (answerIndex === quizQuestions[currentQuestion].correctAnswer) {
      setQuizScore(quizScore + 1);
    }
  };\n\n`;

    code += `  const handleNextQuestion = () => {
    if (currentQuestion < quizQuestions.length - 1) {
      setCurrentQuestion(currentQuestion + 1);
      setSelectedAnswer(null);
    } else {
      setQuizComplete(true);
    }
  };\n\n`;
  }

  if (activities.some((a) => a.type === 'reflection')) {
    code += `  const handleSubmitReflection = async () => {
    if (reflectionResponse.trim().length < ${
      activities.find((a) => a.type === 'reflection')?.props.minResponseLength || 100
    }) {
      setFeedback('Please provide a more detailed reflection (at least ${
        activities.find((a) => a.type === 'reflection')?.props.minResponseLength || 100
      } words).');
      setShowFeedback(true);
      setNeedsRetry(true);
      return;
    }

    if (isNonsensical(reflectionResponse)) {
      setFeedback('Your response needs more depth and thoughtfulness. Please try again.');
      setShowFeedback(true);
      setNeedsRetry(true);
      return;
    }

    setIsGeneratingFeedback(true);
    try {
      const aiResponse = await generateEducationFeedback(
        reflectionResponse,
        '${activities.find((a) => a.type === 'reflection')?.props.prompt || 'Reflect on what you learned.'}'
      );

      setFeedback(aiResponse);
      setShowFeedback(true);

      const feedbackIndicatesRetry =
        aiResponse.toLowerCase().includes('does not address') ||
        aiResponse.toLowerCase().includes('please re-read') ||
        aiResponse.toLowerCase().includes('inappropriate language') ||
        aiResponse.toLowerCase().includes('off-topic') ||
        aiResponse.toLowerCase().includes('must elaborate');

      if (feedbackIndicatesRetry) {
        const newAttemptCount = attemptCount + 1;
        setAttemptCount(newAttemptCount);
        if (newAttemptCount >= MAX_ATTEMPTS) {
          setShowEscapeHatch(true);
        }
      }

      setNeedsRetry(feedbackIndicatesRetry);
    } catch (error) {
      console.error('Feedback generation error:', error);
      setFeedback('Unable to generate feedback. Please try again.');
      setNeedsRetry(true);
    } finally {
      setIsGeneratingFeedback(false);
    }
  };\n\n`;

    code += `  const handleTryAgain = () => {
    setReflectionResponse('');
    setFeedback('');
    setShowFeedback(false);
    setNeedsRetry(false);
    // DO NOT reset attemptCount or showEscapeHatch - they persist across retries
  };\n\n`;

    code += `  const handleContinueAnyway = () => {
    console.log('Student bypassed validation after 2 attempts');
    handleActivityComplete();
  };\n\n`;
  }

  if (activities.some((a) => a.type === 'scenario')) {
    code += `  const handleScenarioSubmit = () => {
    if (scenarioResponse.trim().length >= 100) {
      handleActivityComplete();
    }
  };\n\n`;
  }

  if (activities.some((a) => a.type === 'exit-ticket')) {
    code += `  const handleExitTicketSubmit = () => {
    if (exitTicketResponse.trim().length >= 100) {
      handleActivityComplete();
    }
  };\n\n`;
  }

  return code;
}

/**
 * Generate standard handlers (progress, completion, etc.)
 */
function generateStandardHandlers(): string {
  return `  const handleActivityComplete = () => {
    const updated = [...activities];
    updated[currentActivity].completed = true;
    setActivities(updated);

    if (currentActivity < activities.length - 1) {
      setCurrentActivity(currentActivity + 1);
    } else {
      setCurrentActivity(activities.length); // Move to certificate
    }
  };

  const handleCertificateDownload = () => {
    clearProgress(MODULE_ID);
  };

  const handleResumeProgress = () => {
    const progress = loadProgress(MODULE_ID, activities);
    if (progress) {
      setCurrentActivity(progress.currentActivity);
      setActivities(progress.activities);
    }
    setShowResumeDialog(false);
  };

  const handleStartFresh = () => {
    clearProgress(MODULE_ID);
    setShowResumeDialog(false);
  };`;
}

/**
 * Generate Progress Persistence logic
 */
function generateProgressPersistenceLogic(): string {
  return `  // Load progress on mount
  useEffect(() => {
    const progress = loadProgress(MODULE_ID, activities);
    if (progress) {
      setSavedProgress(getProgressSummary(MODULE_ID));
      setShowResumeDialog(true);
    }
  }, []);

  // Register activities with Dev Mode (ONCE on mount)
  useEffect(() => {
    clearRegistry();
    activities.forEach((activity, index) => {
      registerActivity({
        id: activity.id,
        title: activity.title,
        type: 'activity',
        moduleId: MODULE_ID,
        index,
      });
    });
  }, []); // Empty deps - only register once

  // Auto-save progress
  useEffect(() => {
    if (!showResumeDialog && currentActivity > 0) {
      saveProgress(MODULE_ID, currentActivity, activities, MODULE_VERSION);
    }
  }, [currentActivity, activities, showResumeDialog]);`;
}

/**
 * Generate Dev Mode integration logic
 */
function generateDevModeIntegration(): string {
  return `  // Listen for Dev Mode navigation
  useEffect(() => {
    const handleGoToActivity = (event: CustomEvent) => {
      setCurrentActivity(event.detail);
    };
    window.addEventListener('goToActivity', handleGoToActivity as EventListener);
    return () => window.removeEventListener('goToActivity', handleGoToActivity as EventListener);
  }, []);`;
}

/**
 * Generate activity rendering code
 */
function generateActivityRendering(activities: ActivityConfig[]): string {
  let code = '';

  activities.forEach((activity, index) => {
    switch (activity.type) {
      case 'video':
        code += generateVideoRendering(activity, index);
        break;
      case 'quiz':
        code += generateQuizRendering(activity, index);
        break;
      case 'reflection':
        code += generateReflectionRendering(activity, index);
        break;
      case 'scenario':
        code += generateScenarioRendering(activity, index);
        break;
      case 'exit-ticket':
        code += generateExitTicketRendering(activity, index);
        break;
      case 'interactive':
        code += generateInteractiveRendering(activity, index);
        break;
      default:
        code += generatePlaceholderRendering(activity, index);
    }
    code += '\n\n';
  });

  return code;
}

function generateVideoRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-4xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-6">
                <h2 className="text-xl font-bold text-gray-900 mb-4">${activity.name}</h2>

                {/* TODO: Add PremiumVideoPlayer with segments */}
                <div className="bg-gray-100 rounded-lg p-8 text-center">
                  <p className="text-gray-600">Video player will be rendered here</p>
                  <p className="text-xs text-gray-500 mt-2">Video URL: ${activity.props.videoUrl || 'Not specified'}</p>
                </div>

                <Button
                  onClick={handleActivityComplete}
                  className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                >
                  Mark Complete & Continue
                </Button>
              </div>
            </div>
          )}`;
}

function generateQuizRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-3xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">${activity.name}</h2>

                {!quizComplete ? (
                  <div>
                    <p className="text-lg font-semibold text-gray-800 mb-4">
                      Question {currentQuestion + 1} of {quizQuestions.length}
                    </p>
                    <p className="text-gray-900 mb-6">
                      {quizQuestions[currentQuestion].question}
                    </p>

                    <div className="space-y-3 mb-6">
                      {quizQuestions[currentQuestion].options.map((option: string, idx: number) => (
                        <button
                          key={idx}
                          onClick={() => handleQuizAnswer(idx)}
                          disabled={selectedAnswer !== null}
                          className={\`w-full p-4 text-left rounded-lg border-2 transition-colors \${
                            selectedAnswer === idx
                              ? idx === quizQuestions[currentQuestion].correctAnswer
                                ? 'border-green-500 bg-green-50 text-green-900'
                                : 'border-red-500 bg-red-50 text-red-900'
                              : selectedAnswer !== null && idx === quizQuestions[currentQuestion].correctAnswer
                              ? 'border-green-500 bg-green-50 text-green-900'
                              : 'border-gray-300 bg-white hover:border-purple-300 hover:bg-purple-50 text-gray-900'
                          }\`}
                        >
                          <div className="flex items-start gap-3">
                            <span className="font-bold">{String.fromCharCode(65 + idx)}.</span>
                            <span>{option}</span>
                          </div>
                        </button>
                      ))}
                    </div>

                    {selectedAnswer !== null && (
                      <div className={\`p-4 rounded-lg \${
                        selectedAnswer === quizQuestions[currentQuestion].correctAnswer
                          ? 'bg-green-50 border border-green-200'
                          : 'bg-red-50 border border-red-200'
                      }\`}>
                        <p className="text-sm font-semibold text-gray-900 mb-2">
                          {selectedAnswer === quizQuestions[currentQuestion].correctAnswer
                            ? '✅ Correct!'
                            : '❌ Incorrect'}
                        </p>
                        <p className="text-sm text-gray-800">
                          {quizQuestions[currentQuestion].explanation}
                        </p>
                      </div>
                    )}

                    {selectedAnswer !== null && (
                      <Button
                        onClick={handleNextQuestion}
                        className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                      >
                        {currentQuestion < quizQuestions.length - 1 ? 'Next Question' : 'Complete Quiz'}
                      </Button>
                    )}
                  </div>
                ) : (
                  <div className="text-center">
                    <p className="text-2xl font-bold text-green-600 mb-4">Quiz Complete!</p>
                    <p className="text-gray-700 mb-6">
                      You got {quizScore} out of {quizQuestions.length} correct.
                    </p>
                    <Button
                      onClick={handleActivityComplete}
                      className="bg-purple-600 hover:bg-purple-700 text-white"
                    >
                      Continue to Next Activity
                    </Button>
                  </div>
                )}
              </div>
            </div>
          )}`;
}

function generateReflectionRendering(activity: ActivityConfig, index: number): string {
  const minLength = activity.props.minResponseLength || 100;
  const prompt = activity.props.prompt || 'Reflect on what you learned in this activity.';

  return `          {currentActivity === ${index} && (
            <div className="max-w-3xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">${activity.name}</h2>

                <div className="mb-6 p-4 bg-purple-50 border border-purple-200 rounded-lg">
                  <p className="text-gray-900">${prompt}</p>
                </div>

                <textarea
                  value={reflectionResponse}
                  onChange={(e) => setReflectionResponse(e.target.value)}
                  placeholder="Type your reflection here... (minimum ${minLength} words)"
                  className="w-full p-4 border border-gray-300 rounded-lg text-gray-900 focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  rows={8}
                  disabled={showFeedback && !needsRetry}
                />

                <p className="text-sm text-gray-600 mt-2">
                  {reflectionResponse.split(/\\s+/).filter((w: string) => w.length > 0).length} / ${minLength} words
                </p>

                {showFeedback && (
                  <div className={\`mt-6 p-4 rounded-lg border-2 \${
                    needsRetry ? 'bg-yellow-50 border-yellow-300' : 'bg-green-50 border-green-300'
                  }\`}>
                    <p className="text-sm font-semibold text-gray-900 mb-2">
                      {needsRetry ? '⚠️ Feedback:' : '✅ Great reflection!'}
                    </p>
                    <p className="text-sm text-gray-800">{feedback}</p>
                  </div>
                )}

                {showEscapeHatch && needsRetry && (
                  <div className="mt-6 p-4 bg-orange-50 border-2 border-orange-300 rounded-lg">
                    <p className="text-sm font-semibold text-orange-900 mb-3">
                      ⚠️ You've attempted this reflection {attemptCount} times. Choose one:
                    </p>
                    <div className="flex gap-3">
                      <Button
                        onClick={handleTryAgain}
                        variant="outline"
                        className="flex-1 border-orange-300 text-orange-700 hover:bg-orange-100"
                      >
                        Try One More Time
                      </Button>
                      <Button
                        onClick={handleContinueAnyway}
                        className="flex-1 bg-orange-600 hover:bg-orange-700 text-white"
                      >
                        Continue Anyway
                      </Button>
                    </div>
                    <p className="text-xs text-orange-600 mt-2">
                      Note: Bypassing will be flagged for instructor review.
                    </p>
                  </div>
                )}

                {!showFeedback && !(showEscapeHatch && needsRetry) && (
                  <Button
                    onClick={handleSubmitReflection}
                    disabled={isGeneratingFeedback}
                    className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                  >
                    {isGeneratingFeedback ? 'Analyzing...' : 'Submit Reflection'}
                  </Button>
                )}

                {showFeedback && !needsRetry && (
                  <Button
                    onClick={handleActivityComplete}
                    className="mt-6 bg-green-600 hover:bg-green-700 text-white"
                  >
                    Continue to Next Activity
                  </Button>
                )}

                {showFeedback && needsRetry && !showEscapeHatch && (
                  <Button
                    onClick={handleTryAgain}
                    variant="outline"
                    className="mt-6 border-yellow-600 text-yellow-700 hover:bg-yellow-50"
                  >
                    Try Again
                  </Button>
                )}
              </div>
            </div>
          )}`;
}

function generateScenarioRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-4xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">${activity.name}</h2>

                <div className="mb-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                  <p className="text-sm font-semibold text-blue-900 mb-2">📖 Scenario Context:</p>
                  <p className="text-gray-800">${activity.props.context || 'Scenario context would appear here...'}</p>
                </div>

                <textarea
                  value={scenarioResponse}
                  onChange={(e) => setScenarioResponse(e.target.value)}
                  placeholder="Analyze the ethical dilemma and explain your reasoning..."
                  className="w-full p-4 border border-gray-300 rounded-lg text-gray-900"
                  rows={8}
                />

                <Button
                  onClick={handleScenarioSubmit}
                  disabled={scenarioResponse.trim().length < 100}
                  className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                >
                  Submit Analysis
                </Button>
              </div>
            </div>
          )}`;
}

function generateExitTicketRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-3xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">Exit Ticket</h2>

                <p className="text-gray-700 mb-6">
                  Choose one reflection prompt to complete before finishing this module:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                  {exitTicketPrompts.map((prompt: any, idx: number) => (
                    <div
                      key={idx}
                      onClick={() => setSelectedPrompt(prompt)}
                      className={\`p-4 border-2 rounded-lg cursor-pointer transition-colors \${
                        selectedPrompt === prompt
                          ? 'border-purple-500 bg-purple-50'
                          : 'border-gray-300 bg-white hover:border-purple-300 hover:bg-purple-50'
                      }\`}
                    >
                      <p className="font-medium text-gray-900">{prompt.title}</p>
                    </div>
                  ))}
                </div>

                {selectedPrompt && (
                  <div className="mt-6">
                    <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg mb-4">
                      <p className="text-gray-900">{selectedPrompt.prompt}</p>
                    </div>

                    <textarea
                      value={exitTicketResponse}
                      onChange={(e) => setExitTicketResponse(e.target.value)}
                      placeholder="Type your reflection here..."
                      className="w-full p-4 border border-gray-300 rounded-lg text-gray-900"
                      rows={6}
                    />

                    <Button
                      onClick={handleExitTicketSubmit}
                      disabled={exitTicketResponse.trim().length < 100}
                      className="mt-4 bg-purple-600 hover:bg-purple-700 text-white"
                    >
                      Submit Exit Ticket
                    </Button>
                  </div>
                )}
              </div>
            </div>
          )}`;
}

function generateInteractiveRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-5xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">${activity.name}</h2>

                <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 text-center">
                  <p className="text-gray-700 mb-4">
                    ${activity.props.description || 'Interactive activity placeholder'}
                  </p>
                  <p className="text-sm text-gray-600">
                    ⚠️ Custom interactive component requires manual implementation.
                  </p>
                </div>

                <Button
                  onClick={handleActivityComplete}
                  className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                >
                  Continue to Next Activity
                </Button>
              </div>
            </div>
          )}`;
}

function generatePlaceholderRendering(activity: ActivityConfig, index: number): string {
  return `          {currentActivity === ${index} && (
            <div className="max-w-3xl mx-auto">
              <div className="bg-white rounded-xl shadow-lg p-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6">${activity.name}</h2>

                <div className="bg-gray-100 rounded-lg p-6">
                  <p className="text-gray-700">Activity type "${activity.type}" not yet implemented.</p>
                </div>

                <Button
                  onClick={handleActivityComplete}
                  className="mt-6 bg-purple-600 hover:bg-purple-700 text-white"
                >
                  Continue to Next Activity
                </Button>
              </div>
            </div>
          )}`;
}

function generateHeader(title: string, description: string): string {
  return `        <header className="bg-white shadow-sm border-b border-gray-200">
          <div className="container mx-auto px-4 py-4 flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">${title}</h1>
              <p className="text-sm text-gray-600">${description}</p>
            </div>
            {onClose && (
              <button
                onClick={onClose}
                className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
                aria-label="Close module"
              >
                <X className="w-5 h-5" />
              </button>
            )}
          </div>
        </header>`;
}

function generateCertificate(moduleTitle: string): string {
  return `          {currentActivity === activities.length && (
            <CertificateActivity
              userName={userName}
              moduleName="${moduleTitle}"
              completionDate={new Date().toLocaleDateString()}
              onDownload={handleCertificateDownload}
            />
          )}`;
}

function generateResumeDialog(): string {
  return `      {showResumeDialog && savedProgress && (
        <ResumeProgressDialog
          savedProgress={savedProgress}
          onResume={handleResumeProgress}
          onStartFresh={handleStartFresh}
        />
      )}`;
}

/**
 * Download generated code as .tsx file
 */
export function downloadCode(code: string, filename: string): void {
  const blob = new Blob([code], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
